/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.piotrwalkusz.lebrb.lanlearnservice.api;

import com.piotrwalkusz.lebrb.lanlearnservice.model.LanguagePair;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-24T23:16:06.014Z")

@Api(value = "supported-languages", description = "the supported-languages API")
public interface SupportedLanguagesApi {

    @ApiOperation(value = "Get all pairs of supported languages.", nickname = "supportedLanguagesGet", notes = "Get all pairs of supported languages. A pair is composed of two languages where first is a source language and second is a destination language. ", response = LanguagePair.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = LanguagePair.class, responseContainer = "List") })
    @RequestMapping(value = "/supported-languages",
        method = RequestMethod.GET)
    ResponseEntity<?> supportedLanguagesGet(@ApiParam(value = "Get only pairs of languages where a source language equals given language ", allowableValues = "pl, en, de") @Valid @RequestParam(value = "from", required = false) String from,@ApiParam(value = "Get only pairs of languages where a destination language equals given language ", allowableValues = "pl, en, de") @Valid @RequestParam(value = "to", required = false) String to);

}
